Clang (Release):
  script:
  - git submodule update --init
  - ls -la
  - export CC=clang
  - export CXX=clang++
  - mkdir build
  - cd build
  - cmake -DCMAKE_BUILD_TYPE=Release -DQUBUS_BUILD_TESTS=ON -DHPX_IGNORE_COMPILER_COMPATIBILITY=ON ../
  - make
  - ctest
  tags:
  - docker
  - cuda
GCC (Release):
  script:
  - git submodule update --init
  - ls -la
  - export CC=gcc
  - export CXX=g++
  - mkdir build
  - cd build
  - cmake -DCMAKE_BUILD_TYPE=Release -DQUBUS_BUILD_TESTS=ON -DHPX_IGNORE_COMPILER_COMPATIBILITY=ON ../
  - make
  - ctest
  tags:
  - docker
  - cuda
#Build documentation:
#  script:
#  - ls -la
#  - docker run --rm -v `pwd`:/home/gitlab/Qubus -w /home/gitlab/Qubus td-quantum/archlinux-ci
#    ./build_doc.sh
#  - cp -r build/qubus/doc/* /home/gitlab/doc/latest
#  type: deploy
#  tags:
#  - docker
#  only:
#  - master
