# Currently, we run all test configurations concurrently to optimize for the usual (non failing) case.
# We could also run the debug tests first and abort the entire pipeline if they fail to shorten the build but
# IMHO we would not gain enough speedup to justify the regression in all other cases.
stages:
- test
- build
- deploy

variables:
  GIT_SUBMODULE_STRATEGY: normal

before_script:
  - ./install_ci_dependencies.sh

test:gcc/release:
  script:
  - ls -la
  - export CC=gcc
  - export CXX=g++
  - conan install -g cmake_paths -s build_type=Release -s compiler.libcxx=libstdc++11 -b outdated CI/
  - mkdir build
  - cd build
  - cmake -DCMAKE_TOOLCHAIN_FILE=../conan_paths.cmake -DCMAKE_BUILD_TYPE=Release -DQUBUS_BUILD_TESTS=ON -DQUBUS_UTIL_BUILD_TESTS=ON ../
  - make
  - ctest -E cuda --output-on-failure
  stage: test
  image: ubuntu:18.10

after_script:
  - conan upload -r ci-cache --all boost/1.67.0@conan/stable
  - conan upload -r ci-cache --all hwloc/1.11.10@qubusproject/stable
  - conan upload -r ci-cache --all llvm/8.0.0@qubusproject/stable
  - conan upload -r ci-cache --all hpx/1.3.0@qubusproject/dev
  - conan upload -r ci-cache --all carrot/0.2.0@qubusproject/dev
  - conan upload -r ci-cache --all eigen/3.3.7@conan/stable
  - conan upload -r ci-cache --all isl/0.21@qubusproject/stable
